name: Node.js CI

# Controls when the action will run. This triggers on pushes and pull requests.
on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use the Node.js version that your project supports

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run the build step (compile TypeScript)
      - name: Build TypeScript
        run: npm run build

      # Run the tests
      - name: Run tests
        run: npm test

